development:
  default:
    url: <%= "http://127.0.0.1:8983/solr/development" %>
  full_text:
    url: <%= "http://127.0.0.1:8983/solr/development" %>
test:
  default:
    url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/test
  full_text:
    url: <%= "http://127.0.0.1:#{ENV['SOLR_TEST_PORT'] || 8983}/solr/test" %>
production:
  default:
    url: http://localhost:8080/solr/production
  full_text:
    url: http://localhost:8080/solr/production
