# DRI namespace
module DRI
  # RDFVocabularies namespace
  module RdfVocabularies
    # Defines DRI MARC relationships RDF properties
    class MarcRelatorsVocabulary < RDF::Vocabulary('http://www.loc.gov/marc.relators/')
      property :acp
      property :act
      property :adp
      property :aft
      property :anl
      property :anm
      property :ann
      property :ant
      property :app
      property :aqt
      property :arc
      property :ard
      property :arr
      property :art
      property :asg
      property :asn
      property :att
      property :auc
      property :aud
      property :aui
      property :aus
      property :aut
      property :bdd
      property :bjd
      property :bkd
      property :bkp
      property :bnd
      property :bpd
      property :bsl
      property :ccp
      property :chr
      property :clb
      property :cli
      property :cll
      property :clt
      property :cmm
      property :cmp
      property :cmt
      property :cng
      property :cnd
      property :cns
      property :coe
      property :col
      property :com
      property :cos
      property :cot
      property :cov
      property :cpc
      property :cpe
      property :cph
      property :cpl
      property :cpt
      property :cre
      property :crp
      property :crr
      property :csl
      property :csp
      property :cst
      property :ctb
      property :cte
      property :ctg
      property :ctr
      property :cts
      property :ctt
      property :cur
      property :cwt
      property :dfd
      property :dfe
      property :dft
      property :dgg
      property :dis
      property :dln
      property :dnc
      property :dnr
      property :dpc
      property :dpt
      property :drm
      property :drt
      property :dsr
      property :dst
      property :dtc
      property :dte
      property :dtm
      property :dto
      property :dub
      property :edt
      property :egr
      property :elg
      property :elt
      property :eng
      property :etr
      property :exp
      property :fac
      property :fld
      property :flm
      property :fmo
      property :fpy
      property :fnd
      property :frg
      property :gis
      property :grt
      property :hnr
      property :hst
      property :ill
      property :ilu
      property :ins
      property :inv
      property :itr
      property :ive
      property :ivr
      property :lbr
      property :lbt
      property :ldr
      property :led
      property :lee
      property :lel
      property :len
      property :let
      property :lgd
      property :lie
      property :lil
      property :lit
      property :lsa
      property :lse
      property :lso
      property :ltg
      property :lyr
      property :mcp
      property :mfr
      property :mdc
      property :mod
      property :mon
      property :mrk
      property :msd
      property :mte
      property :mus
      property :nrt
      property :opn
      property :org
      property :orm
      property :oth
      property :own
      property :pat
      property :pbd
      property :pbl
      property :pdr
      property :pfr
      property :pht
      property :plt
      property :pma
      property :pmn
      property :pop
      property :ppm
      property :ppt
      property :prc
      property :prd
      property :prf
      property :prg
      property :prm
      property :pro
      property :prt
      property :pta
      property :pte
      property :ptf
      property :pth
      property :ptt
      property :rbr
      property :rce
      property :rcp
      property :red
      property :ren
      property :res
      property :rev
      property :rps
      property :rpt
      property :rpy
      property :rse
      property :rsg
      property :rsp
      property :rst
      property :rth
      property :rtm
      property :sad
      property :sce
      property :scl
      property :scr
      property :sds
      property :sec
      property :sgn
      property :sht
      property :sng
      property :spk
      property :spn
      property :spy
      property :srv
      property :std
      property :stl
      property :stm
      property :stn
      property :str
      property :tcd
      property :tch
      property :ths
      property :trc
      property :trl
      property :tyd
      property :tyg
      property :vdg
      property :voc
      property :wam
      property :wdc
      property :wde
      property :wit
    end
  end
end
