# DRI namespace
module DRI
  # Vocabulary module
  module Vocabulary
    #
    # @return [Array] array of marcrelator codes
    def self.marc_relators
      ['acp',
       'act',
       'adp',
       'aft',
       'anl',
       'anm',
       'ann',
       'ant',
       'app',
       'aqt',
       'arc',
       'ard',
       'arr',
       'art',
       'asg',
       'asn',
       'att',
       'auc',
       'aud',
       'aui',
       'aus',
       'aut',
       'bdd',
       'bjd',
       'bkd',
       'bkp',
       'bnd',
       'bpd',
       'bsl',
       'ccp',
       'chr',
       'clb',
       'cli',
       'cll',
       'clt',
       'cmm',
       'cmp',
       'cmt',
       'cng',
       'cnd',
       'cns',
       'coe',
       'col',
       'com',
       'cos',
       'cot',
       'cov',
       'cpc',
       'cpe',
       'cph',
       'cpl',
       'cpt',
       'cre',
       'crp',
       'crr',
       'csl',
       'csp',
       'cst',
       'ctb',
       'cte',
       'ctg',
       'ctr',
       'cts',
       'ctt',
       'cur',
       'cwt',
       'dfd',
       'dfe',
       'dft',
       'dgg',
       'dis',
       'dln',
       'dnc',
       'dnr',
       'dpc',
       'dpt',
       'drm',
       'drt',
       'dsr',
       'dst',
       'dtc',
       'dte',
       'dtm',
       'dto',
       'dub',
       'edt',
       'egr',
       'elg',
       'elt',
       'eng',
       'etr',
       'exp',
       'fac',
       'fld',
       'flm',
       'fmo',
       'fpy',
       'fnd',
       'frg',
       'gis',
       'grt',
       'hnr',
       'hst',
       'ill',
       'ilu',
       'ins',
       'inv',
       'itr',
       'ive',
       'ivr',
       'lbr',
       'lbt',
       'ldr',
       'led',
       'lee',
       'lel',
       'len',
       'let',
       'lgd',
       'lie',
       'lil',
       'lit',
       'lsa',
       'lse',
       'lso',
       'ltg',
       'lyr',
       'mcp',
       'mfr',
       'mdc',
       'mod',
       'mon',
       'mrk',
       'msd',
       'mte',
       'mus',
       'nrt',
       'opn',
       'org',
       'orm',
       'oth',
       'own',
       'pat',
       'pbd',
       'pbl',
       'pdr',
       'pfr',
       'pht',
       'plt',
       'pma',
       'pmn',
       'pop',
       'ppm',
       'ppt',
       'prc',
       'prd',
       'prf',
       'prg',
       'prm',
       'pro',
       'prt',
       'pta',
       'pte',
       'ptf',
       'pth',
       'ptt',
       'rbr',
       'rce',
       'rcp',
       'red',
       'ren',
       'res',
       'rev',
       'rps',
       'rpt',
       'rpy',
       'rse',
       'rsg',
       'rsp',
       'rst',
       'rth',
       'rtm',
       'sad',
       'sce',
       'scl',
       'scr',
       'sds',
       'sec',
       'sgn',
       'sht',
       'sng',
       'spk',
       'spn',
       'spy',
       'srv',
       'std',
       'stl',
       'stm',
       'stn',
       'str',
       'tcd',
       'tch',
       'ths',
       'trc',
       'trl',
       'tyd',
       'tyg',
       'vdg',
       'voc',
       'wam',
       'wdc',
       'wde',
       'wit'
      ]
    end

    # Returns a hash of marcrelator codes for creator and their
    # corresponding display values
    #
    # @return [Hash] hash of marcrelator codes for creator
    def self.marc_relators_creator
      { 'aut' => 'Author',
        'art' => 'Artist',
        'att' => 'Attributed name',
        'cre' => 'Creator'
      }
    end

    # Returns a hash of marcrelator codes for contributor and their
    # corresponding display values
    #
    # @return [Hash] hash of marcrelator codes for contributor
    def self.marc_relators_contributor
      { 'ctb' => 'Contributor',
        'pat' => 'Patron',
        'rcp' => 'Addressee'
      }
    end

    # Returns a hash of marcrelator codes and their
    # corresponding display values
    #
    # @return [Hash] hash of marcrelator codes
    def self.marc_relators_display
      { 'abr' => 'Abridger',
        'acp' => 'Art copyist',
        'act' => 'Actor',
        'adi' => 'Art director',
        'adp' => 'Adapter',
        'aft' => 'Author of afterword, colophon, etc.',
        'anl' => 'Analyst',
        'anm' => 'Animator',
        'ann' => 'Annotator',
        'ant' => 'Bibliographic antecedent',
        'ape' => 'Appellee',
        'apl' => 'Appellant',
        'app' => 'Applicant',
        'aqt' => 'Author in quotations or text abstracts',
        'arc' => 'Architect',
        'ard' => 'Artistic director',
        'arr' => 'Arranger',
        'art' => 'Artist',
        'asg' => 'Assignee',
        'asn' => 'Associated name',
        'ato' => 'Autographer',
        'att' => 'Attributed name',
        'auc' => 'Auctioneer',
        'aud' => 'Author of dialog',
        'aui' => 'Author of introduction, etc.',
        'aus' => 'Screenwriter',
        'aut' => 'Author',
        'bdd' => 'Binding designer',
        'bjd' => 'Bookjacket designer',
        'bkd' => 'Book designer',
        'bkp' => 'Book producer',
        'blw' => 'Blurb writer',
        'bnd' => 'Binder',
        'bpd' => 'Bookplate designer',
        'brd' => 'Broadcaster',
        'brl' => 'Braille embosser',
        'bsl' => 'Bookseller',
        'cas' => 'Caster',
        'ccp' => 'Conceptor',
        'chr' => 'Choreographer',
        'cli' => 'Client',
        'cll' => 'Calligrapher',
        'clr' => 'Colorist',
        'clt' => 'Collotyper',
        'cmm' => 'Commentator',
        'cmp' => 'Composer',
        'cmt' => 'Compositor',
        'cnd' => 'Conductor',
        'cng' => 'Cinematographer',
        'cns' => 'Censor',
        'coe' => 'Contestant-appellee',
        'col' => 'Collector',
        'com' => 'Compiler',
        'con' => 'Conservator',
        'cor' => 'Collection registrar',
        'cos' => 'Contestant',
        'cot' => 'Contestant-appellant',
        'cou' => 'Court governed',
        'cov' => 'Cover designer',
        'cpc' => 'Copyright claimant',
        'cpe' => 'Complainant-appellee',
        'cph' => 'Copyright holder',
        'cpl' => 'Complainant',
        'cpt' => 'Complainant-appellant',
        'cre' => 'Creator',
        'crp' => 'Correspondent',
        'crr' => 'Corrector',
        'crt' => 'Court reporter',
        'csl' => 'Consultant',
        'csp' => 'Consultant to a project',
        'cst' => 'Costume designer',
        'ctb' => 'Contributor',
        'cte' => 'Contestee-appellee',
        'ctg' => 'Cartographer',
        'ctr' => 'Contractor',
        'cts' => 'Contestee',
        'ctt' => 'Contestee-appellant',
        'cur' => 'Curator',
        'cwt' => 'Commentator for written text',
        'dbp' => 'Distribution place',
        'dfd' => 'Defendant',
        'dfe' => 'Defendant-appellee',
        'dft' => 'Defendant-appellant',
        'dgg' => 'Degree granting institution',
        'dgs' => 'Degree supervisor',
        'dis' => 'Dissertant',
        'dln' => 'Delineator',
        'dnc' => 'Dancer',
        'dnr' => 'Donor',
        'dpc' => 'Depicted',
        'dpt' => 'Depositor',
        'drm' => 'Draftsman',
        'drt' => 'Director',
        'dsr' => 'Designer',
        'dst' => 'Distributor',
        'dtc' => 'Data contributor',
        'dte' => 'Dedicatee',
        'dtm' => 'Data manager',
        'dto' => 'Dedicator',
        'dub' => 'Dubious author',
        'edc' => 'Editor of compilation',
        'edm' => 'Editor of moving image work',
        'edt' => 'Editor',
        'egr' => 'Engraver',
        'elg' => 'Electrician',
        'elt' => 'Electrotyper',
        'eng' => 'Engineer',
        'enj' => 'Enacting jurisdiction',
        'etr' => 'Etcher',
        'evp' => 'Event place',
        'exp' => 'Expert',
        'fac' => 'Facsimilist',
        'fds' => 'Film distributor',
        'fld' => 'Field director',
        'flm' => 'Film editor',
        'fmd' => 'Film director',
        'fmk' => 'Filmmaker',
        'fmo' => 'Former owner',
        'fmp' => 'Film producer',
        'fnd' => 'Funder',
        'fpy' => 'First party',
        'frg' => 'Forger',
        'gis' => 'Geographic information specialist',
        'his' => 'Host institution',
        'hnr' => 'Honoree',
        'hst' => 'Host',
        'ill' => 'Illustrator',
        'ilu' => 'Illuminator',
        'ins' => 'Inscriber',
        'inv' => 'Inventor',
        'isb' => 'Issuing body',
        'itr' => 'Instrumentalist',
        'ive' => 'Interviewee',
        'ivr' => 'Interviewer',
        'jud' => 'Judge',
        'jug' => 'Jurisdiction governed',
        'lbr' => 'Laboratory',
        'lbt' => 'Librettist',
        'ldr' => 'Laboratory director',
        'led' => 'Lead',
        'lee' => 'Libelee-appellee',
        'lel' => 'Libelee',
        'len' => 'Lender',
        'let' => 'Libelee-appellant',
        'lgd' => 'Lighting designer',
        'lie' => 'Libelant-appellee',
        'lil' => 'Libelant',
        'lit' => 'Libelant-appellant',
        'lsa' => 'Landscape architect',
        'lse' => 'Licensee',
        'lso' => 'Licensor',
        'ltg' => 'Lithographer',
        'lyr' => 'Lyricist',
        'mcp' => 'Music copyist',
        'mdc' => 'Metadata contact',
        'med' => 'Medium',
        'mfp' => 'Manufacture place',
        'mfr' => 'Manufacturer',
        'mod' => 'Moderator',
        'mon' => 'Monitor',
        'mrb' => 'Marbler',
        'mrk' => 'Markup editor',
        'msd' => 'Musical director',
        'mte' => 'Metal-engraver',
        'mtk' => 'Minute taker',
        'mus' => 'Musician',
        'nrt' => 'Narrator',
        'opn' => 'Opponent',
        'org' => 'Originator',
        'orm' => 'Organizer',
        'osp' => 'Onscreen presenter',
        'oth' => 'Other',
        'own' => 'Owner',
        'pan' => 'Panelist',
        'pat' => 'Patron',
        'pbd' => 'Publishing director',
        'pbl' => 'Publisher',
        'pdr' => 'Project director',
        'pfr' => 'Proofreader',
        'pht' => 'Photographer',
        'plt' => 'Platemaker',
        'pma' => 'Permitting agency',
        'pmn' => 'Production manager',
        'pop' => 'Printer of plates',
        'ppm' => 'Papermaker',
        'ppt' => 'Puppeteer',
        'pra' => 'Praeses',
        'prc' => 'Process contact',
        'prd' => 'Production personnel',
        'pre' => 'Presenter',
        'prf' => 'Performer',
        'prg' => 'Programmer',
        'prm' => 'Printmaker',
        'prn' => 'Production company',
        'pro' => 'Producer',
        'prp' => 'Production place',
        'prs' => 'Production designer',
        'prt' => 'Printer',
        'prv' => 'Provider',
        'pta' => 'Patent applicant',
        'pte' => 'Plaintiff-appellee',
        'ptf' => 'Plaintiff',
        'pth' => 'Patent holder',
        'ptt' => 'Plaintiff-appellant',
        'pup' => 'Publication place',
        'rbr' => 'Rubricator',
        'rcd' => 'Recordist',
        'rce' => 'Recording engineer',
        'rcp' => 'Addressee',
        'rdd' => 'Radio director',
        'red' => 'Redaktor',
        'ren' => 'Renderer',
        'res' => 'Researcher',
        'rev' => 'Reviewer',
        'rpc' => 'Radio producer',
        'rps' => 'Repository',
        'rpt' => 'Reporter',
        'rpy' => 'Responsible party',
        'rse' => 'Respondent-appellee',
        'rsg' => 'Restager',
        'rsp' => 'Respondent',
        'rsr' => 'Restorationist',
        'rst' => 'Respondent-appellant',
        'rth' => 'Research team head',
        'rtm' => 'Research team member',
        'sad' => 'Scientific advisor',
        'sce' => 'Scenarist',
        'scl' => 'Sculptor',
        'scr' => 'Scribe',
        'sds' => 'Sound designer',
        'sec' => 'Secretary',
        'sgd' => 'Stage director',
        'sgn' => 'Signer',
        'sht' => 'Supporting host',
        'sll' => 'Seller',
        'sng' => 'Singer',
        'spk' => 'Speaker',
        'spn' => 'Sponsor',
        'spy' => 'Second party',
        'srv' => 'Surveyor',
        'std' => 'Set designer',
        'stg' => 'Setting',
        'stl' => 'Storyteller',
        'stm' => 'Stage manager',
        'stn' => 'Standards body',
        'str' => 'Stereotyper',
        'tcd' => 'Technical director',
        'tch' => 'Teacher',
        'ths' => 'Thesis advisor',
        'tld' => 'Television director',
        'tlp' => 'Television producer',
        'trc' => 'Transcriber',
        'trl' => 'Translator',
        'tyd' => 'Type designer',
        'tyg' => 'Typographer',
        'uvp' => 'University place',
        'vac' => 'Voice actor',
        'vdg' => 'Videographer',
        'wac' => 'Writer of added commentary',
        'wal' => 'Writer of added lyrics',
        'wam' => 'Writer of accompanying material',
        'wat' => 'Writer of added text',
        'wdc' => 'Woodcutter',
        'wde' => 'Wood engraver',
        'win' => 'Writer of introduction',
        'wit' => 'Witness',
        'wpr' => 'Writer of preface',
        'wst' => 'Writer of supplementary textual content'
      }
    end

    # Return the controlled list of values for dcterms:DCMIType
    # vocabulary
    # @return [Array<String>] array of DCMIType values
    def self.dcmi_type
      ['Collection',
       'Dataset',
       'Event',
       'Image',
       'InteractiveResource',
       'MovingImage',
       'PhysicalObject',
       'Service',
       'Software',
       'Sound',
       'StillImage',
       'Text'
      ]
    end

    # Returns a hash of marc codes for type and their
    # corresponding display values
    #
    # @return [Hash] hash of marc codes for type
    def self.marc_type
      { 'a' => 'Language material',
        'c' => 'Notated music',
        'd' => 'Manuscript notated music',
        'e' => 'Cartographic material',
        'f' => 'Manuscript cartographic material',
        'g' => 'Projected medium',
        'i' => 'Nonmusical sound recording',
        'j' => 'Musical sound recording',
        'k' => 'Two-dimensional nonprojectable graphic',
        'm' => 'Computer File',
        'o' => 'Kit',
        'p' => 'Mixed materials',
        'r' => 'Three-dimensional artifact or naturally occurring object',
        't' => 'Manuscript language material' }
    end

    # Returns a hash of marc leader character 6 options and their
    # corresponding display values
    #
    # @return [Hash] hash of marc leader character 6 values
    def self.marc_type_leader_6
      { 'a' => 'Language material',
        'c' => 'Notated music',
        'd' => 'Manuscript notated music',
        'e' => 'Cartographic material',
        'f' => 'Manuscript cartographic material',
        'g' => 'Projected medium',
        'i' => 'Nonmusical sound recording',
        'j' => 'Musical sound recording',
        'k' => 'Two-dimensional nonprojectable graphic',
        'm' => 'Computer File',
        'o' => 'Kit',
        'p' => 'Mixed materials',
        'r' => 'Three-dimensional artifact or naturally occurring object',
        't' => 'Manuscript language material' }
    end

    # Returns a hash of marc leader character 7 options and their
    # corresponding display values
    #
    # @return [Hash] hash of marc leader character 7 values
    def self.marc_type_leader_7
      { 'a' => 'Monographic component part',
        'b' => 'Serial component part',
        'c' => 'Collection',
        'd' => 'Subunit',
        'i' => 'Integrating resource',
        'm' => 'Monograph/Item',
        's' => 'Serial' }
    end

    # Array [ Decimal Classification Number (R), First Indicator, Second Indicator, Subfield Code ]
    # :code = datafield no, :ind1 = indicator1, :ind2 = indicator2, :sf = subfield
    # Below you shove in any sf except the mandatory fields
    # NCCB Required Fields
    def self.marc_data_fields
      [{ code: '010', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '015', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '016', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '020', ind1: ' ', ind2: ' ', sf: ['a', 'c'] },
       { code: '040', ind1: ' ', ind2: ' ', sf: ['a', 'c', 'd'] },
       { code: '041', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '042', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '050', ind1: '0', ind2: '0', sf: ['a', 'b'] },
       { code: '082', ind1: '0', ind2: '0', sf: ['a', '2'] },
       { code: '083', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '100', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '110', ind1: '1', ind2: ' ', sf: ['a', 'd'] },
       { code: '111', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '222', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '240', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '245', ind1: '1', ind2: '0', sf: ['a', 'c'] },
       { code: '248', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '250', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '255', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '260', ind1: ' ', ind2: ' ', sf: ['a', 'b', 'c'] },
       { code: '264', ind1: ' ', ind2: ' ', sf: ['c'] },
       { code: '300', ind1: ' ', ind2: ' ', sf: ['a', 'b', 'c'] },
       { code: '336', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '350', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '490', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '500', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '501', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '503', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '504', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '505', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '506', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '514', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '520', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '530', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '531', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '540', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '542', ind1: ' ', ind2: ' ', sf: ['f'] },
       { code: '546', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '561', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '563', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '600', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '610', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '611', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '650', ind1: ' ', ind2: '1', sf: ['a'] },
       { code: '651', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '655', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '700', ind1: '1', ind2: ' ', sf: ['a', 'e'] },
       { code: '710', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '711', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '740', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '745', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '900', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '910', ind1: ' ', ind2: ' ', sf: ['a'] },
       { code: '997', ind1: ' ', ind2: ' ', sf: ['a'] }
      ]
    end

    # Returns an array of MODS Relationship Types
    # @return [Array<String>] the array of MODS rels types
    def self.mods_relationship_types
      ['preceding',
       'succeeding',
       'original',
       'host',
       'constituent',
       'series',
       'otherVersion',
       'otherFormat',
       'isReferencedBy',
       'references',
       'reviewOf'
      ]
    end

    # Returns an array of QDC Relationship Types
    # @return [Array<String>] the array of QDC rels types
    def self.qdc_relationship_types
      ['relation',
       'isPartOf',
       'hasPart',
       'isReferencedBy',
       'references',
       'isVersionOf',
       'hasVersion',
       'isFormatOf',
       'hasFormat',
       'source'
      ]
    end

    # Returns an array of possible values for the level attribute
    # of ead:c, ead:c01-ead:c12 component tags
    # @return [Array<String>] the array of values for level attribute
    def self.ead_level_values
      ['collection',
       'fonds',
       'class',
       'recordgrp',
       'series',
       'subfonds',
       'subgrp',
       'subseries',
       'file',
       'item',
       'otherlevel'
      ]
    end

    # Returns an array of EAD people tags than can be used within
    # ead:origination elements
    # @return [Array<String>] the array of ead:origination nested people tags
    def self.ead_people_tags
      ['name',
       'persname',
       'corpname',
       'famnane']
    end

    # Returns an array of MODS date tags than can be used within
    # mods:originInfo elements
    # @return [Array<String>] the array of mods:originInfo nested date tags
    def self.mods_date_tags
      ['dateCreated',
       'dateIssued',
       'dateCaptured', # tech md
       'dateOther',
       'dateValid', # tech md
       'dateModified', # tech md
       'copyrightDate',
       'temporal'
      ]
    end

    # Returns an array of MODS tags than can be used within
    # mods:originInfo elements
    # @return [Array<String>] the array of mods:originInfo nested tags
    def self.mods_origin_info_tags
      ['dateCreated',
       'dateIssued',
       'dateCaptured', # tech md
       'dateOther',
       'dateValid', # tech md
       'dateModified', # tech md
       'copyrightDate',
       'place',
       'issuance',
       'edition',
       'frequency',
       'publisher'
      ]
    end

    # Returns an array of MODS possible values for the content of mods:typeOfResource
    # @return [Array<String>] the array of values for mods:typeOfResource
    def self.mods_type_resource_values
      [ 'text',
        'cartographic',
        'notated music',
        'sound recording',
        'sound recording-nonmusical',
        'still image',
        'moving image',
        'three dimensional object',
        'software, multimedia',
        'mixed material'
      ]
    end

    # Returns an array of MODS encoding values for dates
    # @return [Array<String>] the array of date encoding values
    def self.mods_date_encoding
      ['iso8601', 'w3cdtf']
    end

    # Determines whether the values for the metadata field should be indexed
    # Used in DRI::Metadata::Mods for MODS role_cre and role_ctb fields
    # @return [Boolean>] true if can be indexed; false otherwise
    def self.marc_relators_index?(code)
      return false if code == 'cre' || code == 'ctb'

      true
    end
  end
end
