module DRI
  module Vocabulary
  	def self.marcRelators
      [
        "acp",
        "act",
        "adp",
        "aft",
        "anl",
        "anm",
        "ann",
        "ant",
        "app",
        "aqt",
        "arc",
        "ard",
        "arr",
        "art",
        "asg",
        "asn",
        "att",
        "auc",
        "aud",
        "aui",
        "aus",
        "aut",
        "bdd",
        "bjd",
        "bkd",
        "bkp",
        "bnd",
        "bpd",
        "bsl",
        "ccp",
        "chr",
        "clb",
        "cli",
        "cll",
        "clt",
        "cmm",
        "cmp",
        "cmt",
        "cng",
        "cnd",
        "cns",
        "coe",
        "col",
        "com",
        "cos",
        "cot",
        "cov",
        "cpc",
        "cpe",
        "cph",
        "cpl",
        "cpt",
        "cre",
        "crp",
        "crr",
        "csl",
        "csp",
        "cst",
        "ctb",
        "cte",
        "ctg",
        "ctr",
        "cts",
        "ctt",
        "cur",
        "cwt",
        "dfd",
        "dfe",
        "dft",
        "dgg",
        "dis",
        "dln",
        "dnc",
        "dnr",
        "dpc",
        "dpt",
        "drm",
        "drt",
        "dsr",
        "dst",
        "dtc",
        "dte",
        "dtm",
        "dto",
        "dub",
        "edt",
        "egr",
        "elg",
        "elt",
        "eng",
        "etr",
        "exp",
        "fac",
        "fld",
        "flm",
        "fmo",
        "fpy",
        "fnd",
        "frg",
        "gis",
        "grt",
        "hnr",
        "hst",
        "ill",
        "ilu",
        "ins",
        "inv",
        "itr",
        "ive",
        "ivr",
        "lbr",
        "lbt",
        "ldr",
        "led",
        "lee",
        "lel",
        "len",
        "let",
        "lgd",
        "lie",
        "lil",
        "lit",
        "lsa",
        "lse",
        "lso",
        "ltg",
        "lyr",
        "mcp",
        "mfr",
        "mdc",
        "mod",
        "mon",
        "mrk",
        "msd",
        "mte",
        "mus",
        "nrt",
        "opn",
        "org",
        "orm",
        "oth",
        "own",
        "pat",
        "pbd",
        "pbl",
        "pdr",
        "pfr",
        "pht",
        "plt",
        "pma",
        "pmn",
        "pop",
        "ppm",
        "ppt",
        "prc",
        "prd",
        "prf",
        "prg",
        "prm",
        "pro",
        "prt",
        "pta",
        "pte",
        "ptf",
        "pth",
        "ptt",
        "rbr",
        "rce",
        "rcp",
        "red",
        "ren",
        "res",
        "rev",
        "rps",
        "rpt",
        "rpy",
        "rse",
        "rsg",
        "rsp",
        "rst",
        "rth",
        "rtm",
        "sad",
        "sce",
        "scl",
        "scr",
        "sds",
        "sec",
        "sgn",
        "sht",
        "sng",
        "spk",
        "spn",
        "spy",
        "srv",
        "std",
        "stl",
        "stm",
        "stn",
        "str",
        "tcd",
        "tch",
        "ths",
        "trc",
        "trl",
        "tyd",
        "tyg",
        "vdg",
        "voc",
        "wam",
        "wdc",
        "wde",
        "wit"
      ]
    end

    def self.dcmiType
      [
        "Collection",
        "Dataset",
        "Event",
        "Image",
        "InteractiveResource",
        "MovingImage",
        "PhysicalObject",
        "Service",
        "Software",
        "Sound",
        "StillImage",
        "Text"
      ]
    end

    # Array [ Decimal Classification Number (R), First Indicator, Second Indicator, Subfield Code ]
    # :code = datafield no, :ind1 = indicator1, :ind2 = indicator2, :sf = subfield
    # Below you shove in any sf except the mandatory fields
    # NCCB Required Fields
    def self.marcDatafields
      [
        {:code => "015", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "016", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "020", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "040", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "041", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "082", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "083", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "100", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "110", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "111", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "222", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "240", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "245", :ind1 => " ", :ind2 => " ", :sf => ["a", "c"]},
        {:code => "248", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "250", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "255", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "260", :ind1 => " ", :ind2 => " ", :sf => ["a", "c"]},
        {:code => "300", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "336", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "350", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "490", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "500", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "501", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "503", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "504", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "505", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "506", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "514", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "530", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "531", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "546", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "561", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "563", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "600", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "610", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "611", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "650", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "651", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "655", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "700", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "710", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "740", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "745", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "900", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "910", :ind1 => " ", :ind2 => " ", :sf => ["a"]},
        {:code => "997", :ind1 => " ", :ind2 => " ", :sf => ["a"]}
      ]
    end
  end
end
